import 'package:uuid/uuid.dart';
import '../models/user.dart';
import '../models/trip.dart';
import '../models/expense.dart';
import '../models/card.dart';

class DummyData {
  static const uuid = Uuid();

  // Dummy Users
  static User dummyUser = User(
    id: uuid.v4(),
    name: 'John Doe',
    email: 'john.doe@company.com',
    profileImage: null,
    department: 'Sales',
    phone: '+1 (555) 123-4567',
    role: 'Employee',
    isActive: true,
    createdAt: DateTime.now().subtract(const Duration(days: 365)),
  );

  // Dummy Trips
  static List<Trip> dummyTrips = [
    Trip(
      id: uuid.v4(),
      userId: dummyUser.id,
      destination: 'San Francisco, CA',
      purpose: 'Client Meeting & Conference',
      startDate: DateTime.now().add(const Duration(days: 5)),
      endDate: DateTime.now().add(const Duration(days: 8)),
      status: 'Upcoming',
      budget: 2000,
      spent: 1450.50,
      hotelName: 'Hilton San Francisco',
      flightNumber: 'UA456',
      travelers: ['John Doe', 'Jane Smith'],
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
    ),
    Trip(
      id: uuid.v4(),
      userId: dummyUser.id,
      destination: 'New York, NY',
      purpose: 'Board Meeting',
      startDate: DateTime.now().subtract(const Duration(days: 15)),
      endDate: DateTime.now().subtract(const Duration(days: 12)),
      status: 'Completed',
      budget: 1500,
      spent: 1200.00,
      hotelName: 'Marriott Manhattan',
      flightNumber: 'AA123',
      travelers: ['John Doe', 'Mike Johnson'],
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
    ),
    Trip(
      id: uuid.v4(),
      userId: dummyUser.id,
      destination: 'Austin, TX',
      purpose: 'Tech Conference',
      startDate: DateTime.now().add(const Duration(days: 20)),
      endDate: DateTime.now().add(const Duration(days: 23)),
      status: 'Upcoming',
      budget: 1800,
      spent: 0,
      hotelName: null,
      flightNumber: null,
      travelers: ['John Doe'],
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    Trip(
      id: uuid.v4(),
      userId: dummyUser.id,
      destination: 'Los Angeles, CA',
      purpose: 'Product Launch',
      startDate: DateTime.now().subtract(const Duration(days: 45)),
      endDate: DateTime.now().subtract(const Duration(days: 42)),
      status: 'Completed',
      budget: 2500,
      spent: 2350.75,
      hotelName: 'Beverly Hills Hotel',
      flightNumber: 'UA789',
      travelers: ['John Doe', 'Sarah Williams'],
      createdAt: DateTime.now().subtract(const Duration(days: 60)),
    ),
  ];

  // Dummy Expenses
  static List<Expense> dummyExpenses = [
    Expense(
      id: uuid.v4(),
      userId: dummyUser.id,
      tripId: dummyTrips[0].id,
      category: 'Flight',
      description: 'Round trip flight to San Francisco',
      amount: 650.00,
      currency: 'USD',
      status: 'Approved',
      receiptUrl: null,
      notes: 'Economy class',
      approvedBy: 'Manager',
      date: DateTime.now().subtract(const Duration(days: 2)),
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    Expense(
      id: uuid.v4(),
      userId: dummyUser.id,
      tripId: dummyTrips[0].id,
      category: 'Hotel',
      description: 'Hilton San Francisco - 3 nights',
      amount: 450.00,
      currency: 'USD',
      status: 'Approved',
      receiptUrl: null,
      notes: 'Superior Room',
      approvedBy: 'Manager',
      date: DateTime.now().subtract(const Duration(days: 2)),
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    Expense(
      id: uuid.v4(),
      userId: dummyUser.id,
      tripId: dummyTrips[0].id,
      category: 'Restaurant',
      description: 'Client Dinner at The French Laundry',
      amount: 250.00,
      currency: 'USD',
      status: 'Pending',
      receiptUrl: null,
      notes: 'Business meal with client',
      approvedBy: null,
      date: DateTime.now().subtract(const Duration(days: 1)),
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    Expense(
      id: uuid.v4(),
      userId: dummyUser.id,
      tripId: dummyTrips[0].id,
      category: 'Transport',
      description: 'Uber to conference venue',
      amount: 35.50,
      currency: 'USD',
      status: 'Approved',
      receiptUrl: null,
      notes: 'Daily transportation',
      approvedBy: 'System',
      date: DateTime.now().subtract(const Duration(days: 1)),
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    Expense(
      id: uuid.v4(),
      userId: dummyUser.id,
      tripId: dummyTrips[1].id,
      category: 'Flight',
      description: 'Round trip flight to New York',
      amount: 550.00,
      currency: 'USD',
      status: 'Reimbursed',
      receiptUrl: null,
      notes: null,
      approvedBy: 'Manager',
      date: DateTime.now().subtract(const Duration(days: 20)),
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
    ),
    Expense(
      id: uuid.v4(),
      userId: dummyUser.id,
      tripId: dummyTrips[1].id,
      category: 'Hotel',
      description: 'Marriott Manhattan - 2 nights',
      amount: 400.00,
      currency: 'USD',
      status: 'Reimbursed',
      receiptUrl: null,
      notes: null,
      approvedBy: 'Manager',
      date: DateTime.now().subtract(const Duration(days: 20)),
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
    ),
    Expense(
      id: uuid.v4(),
      userId: dummyUser.id,
      tripId: dummyTrips[1].id,
      category: 'Restaurant',
      description: 'Team Lunch',
      amount: 125.00,
      currency: 'USD',
      status: 'Approved',
      receiptUrl: null,
      notes: 'Team bonding meal',
      approvedBy: 'Manager',
      date: DateTime.now().subtract(const Duration(days: 18)),
      createdAt: DateTime.now().subtract(const Duration(days: 18)),
    ),
    Expense(
      id: uuid.v4(),
      userId: dummyUser.id,
      tripId: dummyTrips[3].id,
      category: 'Flight',
      description: 'Round trip flight to Los Angeles',
      amount: 680.00,
      currency: 'USD',
      status: 'Reimbursed',
      receiptUrl: null,
      notes: null,
      approvedBy: 'Manager',
      date: DateTime.now().subtract(const Duration(days: 50)),
      createdAt: DateTime.now().subtract(const Duration(days: 50)),
    ),
    Expense(
      id: uuid.v4(),
      userId: dummyUser.id,
      tripId: dummyTrips[3].id,
      category: 'Hotel',
      description: 'Beverly Hills Hotel - 3 nights',
      amount: 750.00,
      currency: 'USD',
      status: 'Reimbursed',
      receiptUrl: null,
      notes: null,
      approvedBy: 'Manager',
      date: DateTime.now().subtract(const Duration(days: 50)),
      createdAt: DateTime.now().subtract(const Duration(days: 50)),
    ),
    Expense(
      id: uuid.v4(),
      userId: dummyUser.id,
      tripId: dummyTrips[3].id,
      category: 'Entertainment',
      description: 'Event tickets for product launch',
      amount: 200.00,
      currency: 'USD',
      status: 'Reimbursed',
      receiptUrl: null,
      notes: 'Team event',
      approvedBy: 'Manager',
      date: DateTime.now().subtract(const Duration(days: 48)),
      createdAt: DateTime.now().subtract(const Duration(days: 48)),
    ),
  ];

  // Dummy Corporate Cards
  static List<CorporateCard> dummyCards = [
    CorporateCard(
      id: uuid.v4(),
      userId: dummyUser.id,
      cardNumber: '4532123456789012',
      cardHolder: 'JOHN DOE',
      cardType: 'Visa',
      status: 'Active',
      spendLimit: 5000,
      spent: 3850.50,
      expiryDate: DateTime(2027, 12),
      issuedDate: DateTime(2022, 1),
    ),
    CorporateCard(
      id: uuid.v4(),
      userId: dummyUser.id,
      cardNumber: '5425123456789012',
      cardHolder: 'JOHN DOE',
      cardType: 'Mastercard',
      status: 'Active',
      spendLimit: 3000,
      spent: 1200.00,
      expiryDate: DateTime(2026, 8),
      issuedDate: DateTime(2021, 6),
    ),
    CorporateCard(
      id: uuid.v4(),
      userId: dummyUser.id,
      cardNumber: '378282246310005',
      cardHolder: 'JOHN DOE',
      cardType: 'Amex',
      status: 'Active',
      spendLimit: 10000,
      spent: 5420.75,
      expiryDate: DateTime(2028, 3),
      issuedDate: DateTime(2023, 2),
    ),
  ];
}
